apiVersion: v1
kind: Pod
metadata:
    name: log-generator
    labels:
        app: log-generator
spec:
    containers:
        - name: log-generator
          image: apache-log-generator_apache
          imagePullPolicy: Never
