version: '3.2'

services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  elastalert:
    image: 'servercentral/elastalert'
    ports:
      - '3030:3030'
      - '3333:3333'
    volumes:
      - ./praeco/config/elastalert.yaml:/opt/elastalert/config.yaml
      - ./praeco/config/api.config.json:/opt/elastalert-server/config/config.json
      - ./praeco/rules:/opt/elastalert/rules
      - ./praeco/rule_templates:/opt/elastalert/rule_templates
    networks:
      - elk
    depends_on:
      - elasticsearch

  praeco:
    image: 'servercentral/praeco'
    ports:
      - '8080:8080'
    volumes:
      - ./praeco/public/praeco.config.json:/var/www/html/praeco.config.json
      - ./praeco/nginx_config/nginx.conf:/etc/nginx/nginx.conf
      - ./praeco/nginx_config/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - elk
    depends_on:
      - elasticsearch

  webapp:
    build:
      context: apache-log-generator/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
    - type: bind
      source: ./apache-log-generator/log/
      target: /var/log/
    networks:
      - elk
    depends_on:
      - elasticsearch
      - logstash

  filebeat:
    image: "docker.elastic.co/beats/filebeat:$ELK_VERSION"
    user: root
    volumes:
    - type: bind
      source: ./filebeat/filebeat.yml
      target: /usr/share/filebeat/filebeat.yml
      read_only: true
    - type: bind
      source: ./apache-log-generator/log/
      target: /var/log/apache_access
      read_only: true
    networks:
      - elk
    depends_on:
      - webapp
      - logstash
      
networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
